import { Geist, Geist_Mono, Agbalumo } from "next/font/google";
import "./globals.css";

import { Toaster } from "react-hot-toast";
import LayoutConditionalWrapper from "@/components/LayoutConditionalWraper";
import { Providers } from "@/components/Providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const agbalumo = Agbalumo({
  variable: "--font-agbalumo",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
     
      className={`${geistSans.variable} ${geistMono.variable}  ${agbalumo.variable} h-full  dark`}suppressHydrationWarning
    >
      <body className=" flex flex-col min-h-screen antialiased ">
       <Providers>
        <LayoutConditionalWrapper>
        {children}
        
</LayoutConditionalWrapper>
          <Toaster />
          </Providers>
        </body>
    </html>
  );
}
